language: java
jdk:
  - oraclejdk11

cache:
  directories:
    - "$HOME/.m2"

deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  app: application
  env: application
  zip_file: 'app/target/app.jar'
  access_key_id:
    secure: AKIAJVYT7PZNNSPMYW7A
  secret_access_key:
    secure: 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
  region: ap-southeast-1
  bucket: elasticbeanstalk-ap-southeast-1-226923330965
  on:
    repo: raffiditya/astrafinancial-mini-assignment
    branch: master
